version: '3.8'

services:
  healthtrack-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://db:5432/healthtrack
      - DATABASE_USERNAME=healthtrack
      - DATABASE_PASSWORD=password
    depends_on:
      - db
    networks:
      - healthtrack-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=healthtrack
      - POSTGRES_USER=healthtrack
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthtrack-network

  # SonarQube para análisis local
  sonarqube:
    image: sonarqube:9.9-community
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar-db
    networks:
      - healthtrack-network

  sonar-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonar_postgres_data:/var/lib/postgresql/data
    networks:
      - healthtrack-network

volumes:
  postgres_data:
  sonar_postgres_data:

networks:
  healthtrack-network:
    driver: bridge